
<p><strong> Server-Related Local Links </strong></p>
<ul>

<li><a target="_blank"  href="https://youtube.com">YouTube</a></li>

<li>Sample Images 
 :: <a target="_blank"  href="https://instagr.am/">Instagram</a>
 :: <a target="_blank"  href="https://flickr.com/">Flickr</a>
</li>

<li>Sample Social Media
 :: <a target="_blank"  href="https://facebook.com">Facbook</a>
 :: <a target="_blank"  href="https://twitter.com">Twitter</a>
</li>


</ul>

